{{- if .Values.argus.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.argus.secret.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.argus.secret.annotations }}
  annotations:
    {{ toYaml .Values.argus.secret.annotations }}
  {{- end }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    {{- if .Values.argus.secret.extraLabels }}
    {{- toYaml .Values.argus.secret.extraLabels | indent 4 }}
    {{- end }}
type: Opaque
data:
  config.yml: {{ .Values.argus.config | b64enc }}
{{- end }}
