{{- if .Values.argus.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.argus.serviceAccount.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.argus.serviceAccount.annotations }}
  annotations:
    {{ toYaml .Values.argus.serviceAccount.annotations }}
  {{- end }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
    {{- if .Values.argus.serviceAccount.extraLabels }}
    {{- toYaml .Values.argus.serviceAccount.extraLabels | indent 4 }}
    {{- end }}
{{- end }}
